# Generated by Django 5.2 on 2025-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
